

export default {
  ARTICLE_NOTIFICATION_EVENT: 'ARTICLE_NOTIFICATION_EVENT',
  COMMENT_NOTIFICATION_EVENT: 'COMMENT_NOTIFICATION_EVENT',
  RATING_INTERACTION_EVENT: 'RATING_INTERACTION_EVENT,',
  FOLLOW_INTERACTION_EVENT: 'FOLLOW_INTERACTION_EVENT',
  UPDATEHIGHLIGHT_EVENT: 'UPDATEHIGHLIGHT_EVENT'
};
