

export default {
  ARTICLE_NOTIFICATION_EVENT: 'ARTICLE_NOTIFICATION_EVENT',
  COMMENT_NOTIFICATION_EVENT: 'COMMENT_NOTIFICATION_EVENT',
  RATING_INTERACTION_EVENT: 'RATING_INTERACTION_EVENT,',
  FOLLOW_INTERACTION_EVENT: 'FOLLOW_INTERACTION_EVENT',
  UPDATEHIGHLIGHT_EVENT: 'UPDATEHIGHLIGHT_EVENT',
  POST_ARTICLE_NOTIFICATION: 'POST_ARTICLE_NOTIFICATION',
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  LIKED: 'LIKED',
  RATED: 'RATED',
  COMMENTED: 'COMMENTED',
  FOLLOWED: 'FOLLOWED',
  NEW_ARTICLE: 'NEW ARTICLE'
};
